CREATE TABLE POINT_OF_INTEREST (
    ID INT PRIMARY KEY,
    LAN REAL,
    LOT REAL,
    NAME VARCHAR(255)
);

CREATE TABLE TIME_OF_DAY (
    ID INT PRIMARY KEY,
    LEFT_HOUR INT,
    RIGHT_HOUR INT,
    NAME VARCHAR(255)
);

CREATE TABLE NOISE_LEVEL (
    ID INT PRIMARY KEY,
    LEFT_DB REAL,
    RIGHT_DB REAL,
    LEVEL VARCHAR(255)
);

INSERT INTO POINT_OF_INTEREST VALUES(1, 45.4641, 9.1919, 'Duomo di Milano');
INSERT INTO POINT_OF_INTEREST VALUES(2, 41.0086, 28.9802, 'Hagia Sophia');

INSERT INTO TIME_OF_DAY VALUES(1, 4, 10, 'Morning');
INSERT INTO TIME_OF_DAY VALUES(2, 10, 14, 'Midday');
INSERT INTO TIME_OF_DAY VALUES(3, 14, 17, 'Afternoon');
INSERT INTO TIME_OF_DAY VALUES(4, 17, 21, 'Evening');
INSERT INTO TIME_OF_DAY VALUES(5, 21, 23, 'Night');
INSERT INTO TIME_OF_DAY VALUES(6, 23, 4, 'Midnight');

INSERT INTO NOISE_LEVEL VALUES(1, 0, 40, 'Faint');
INSERT INTO NOISE_LEVEL VALUES(2, 40, 60, 'Moderate');
INSERT INTO NOISE_LEVEL VALUES(3, 60, 80, 'Loud');
INSERT INTO NOISE_LEVEL VALUES(4, 80, 100, 'Very loud');
INSERT INTO NOISE_LEVEL VALUES(5, 100, 120, 'Extremely loud');
